name: Build DLL Injector (Auto Commit)

on:
  push:
    paths:
      - '**.cpp'
      - '**.bat'

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86

      - name: Build injector.exe
        run: |
          g++ -static -o injector.exe dll_inject_launcher.cpp

      - name: Commit built .exe back to repo
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add injector.exe
          git commit -m "Auto-commit built injector.exe" || echo "No changes"
          git push
